
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Nav, NavLink } from "../components/Nav";
import "../globals.css";

const poppins = Poppins({  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
     <>
        <Nav>
        <NavLink href="/">Home</NavLink>
        <NavLink href="/admin">Admin</NavLink>
        <NavLink href="/orders">My Orders</NavLink>
      </Nav>
     <div>
            {children}
     </div>
     </>
    );
}
