
import type { Metadata } from "next";
import { Nav } from "./_components/Nav";
import { getServerSession } from "next-auth";
import { authConfig } from "@/lib/auth";
import {redirect} from "next/navigation";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await getServerSession(authConfig);
    if (session && session?.user?.role !== "ADMIN")
    {
        redirect("/");
    }
    
    return (
     <>
      <Nav variation={0}/>
        

     <div>
            {children}
     </div>
     </>
    );
}
