
import type { Metadata } from "next";
import { Nav } from "../components/Nav";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
     <>
        <Nav variation={0}>

      </Nav>
     <div>
            {children}
     </div>
     </>
    );
}
