import type { Metadata } from "next";

import cn from "classnames";
import "./globals.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("h-full w-full bg-default font-satoshi")}>{children}</body>
    </html>
  );
}
